### ISSUE TITLE
Using 'import' instead of require?

### ISSUE THREAD

**Issue by donjae** [wrangr/psl#3]
Hi, 

Trying to use `import` instead of require for the module, but getting an error. I've tried 
`import * as psl from 'psl'` but to no avail. Any input?

**Comment by lupomontero** [comment]
Hi @donjae,

1. Are you getting any error messages in particular?
2. What environment are you running in (ie: web browser, Node.js, ...) and what version?
3. What version of `psl` are you using?
4. Are you using a transpiler (ie: Babel)?

As far as I know ES6 modules are not yet available in Node.js or any major browser. Are you able to `import` other modules? Have you tried _requiring_ the module instead of _importing_ it?

**Comment by donjae** [comment]
Thanks for the response. I actually realized it's an issue with angular2/typescript dealing with 'typing' definitions. And unfortunately, typescript has some kinks where even when I tried using something like `import psl = require('psl')` still created some issues. 

I'll be using this module for my backend too, which has babel. But it should it be fine.
