### ISSUE TITLE
Incorrectly stating a valid URL is invalid

### ISSUE THREAD

**Issue by willigogs** [wrangr/psl#9]
Issue exists where overlapping suffixes aren't handled correctly, and state URL as invalid.

For example:
gov.uk - valid URL since "gov" is the sld, and ".uk" is the tld.  However, this incorrectly states the URL is invalid, since "gov.uk" is also a tld in its own right (e.g. "data.gov.uk", where "data" is the sld and "gov.uk" is the tld).

Same goes for other overlapping tlds, such as github.io.

**Comment by lupomontero** [comment]
Hi @willigogs, apologies for the delay in getting back to you. 

I noticed that `psl.parse('github.io')` (for example) would result in the following object:

```js
{ input: 'github.io',
  tld: null, // this was wrong!
  sld: null,
  domain: null,
  subdomain: null,
  listed: true }
```

I have now updated `psl.parse` so that you should get:

```js
{ input: 'github.io',
  tld: 'github.io', // note that `tld` is now set to `github.io`
  sld: null,
  domain: null,
  subdomain: null,
  listed: true }
```

On the other hand, `psl.isValid('github.io')` will return `false`, because the _domain_ is not under a _public suffix_, `github.io` is the suffix itself. By definition, a "public suffix" is one under which Internet users can directly "register" names, and a valid _domain name_ will be one that is a "subdomain" of a _public suffix_.

Does this address the issue?
